### ISSUE TITLE
Endless echo using MIDI playback on Nexus 9 5.x

### ISSUE THREAD

**Issue by lisawray** [billthefarmer/mididriver#14]
Hi,

First, thanks for your awesome work on this library!!  I can't tell you how much I appreciate it.  I've been searching for MIDI support on Android for a long time.

I've started using the /jhindin branch.  It works great on all other devices I've tried, but on a Nexus 9 running 5.0.1, 5.0.2, or 5.1.1 (the versions I tried) playing even one note produces an unending, increasing echo.  A Nexus 10 running 5.0.2 is fine though,

Please let me know if I can help you debug this.  I'm very familiar with Android but not at all with native code.  Currently, I've updated my Nexus 9 to 6.0 and I can confirm that the problem is not present on that version.  I'm happy to downgrade it to 5.x again starting tonight if you have any suggestions on how to get useful output on the problem. I can also provide a video, etc.

**Comment by billthefarmer** [comment]
This is an issue with 64 bit devices. See closed issue ' Noise on android lollipop 5.1+'. The fix is to not build/remove the 64 bit libraries. I don't know how to do that in the jhindin branch. This branch is also out of date as I have converted the main branch to native audio.

**Comment by lisawray** [comment]
OK, I will try to bring the jhindin branch up to date tonight or convert the current main branch to build with gradle.  Thanks!

**Comment by billthefarmer** [comment]
It looks like smarek (https://github.com/smarek) may have already done it for you. https://github.com/smarek/mididriver. See the now closed issue https://github.com/billthefarmer/mididriver/issues/12#issuecomment-149615860
