### ISSUE TITLE
mididriver is not working on the device of arm64-v8a

### ISSUE THREAD

**Issue by KyoSherlock** [billthefarmer/mididriver#15]
If I have other so files in arm64-v8a, mididriver is not working.

**Comment by billthefarmer** [comment]
The libsonivox.so library sources are written for 32 bit only. See https://github.com/billthefarmer/mididriver/issues/14 and https://github.com/billthefarmer/mididriver/issues/11. Google have built broken 64 bit versions of the library into devices and at least one emulator. I have worked around this by not building/not including 64 bit versions of libmidi.so, forcing devices to use the 32 bit version of libsonivox.so. I assume, by including other native 64 bit libraries in your app, this has been defeated somehow. The obvious workaround is not to build 64 bit versions of your native libraries.

There is probably some limitation on android apps that you can't have both 64 bit and 32 bit native libraries in the same app. Sounds fairly likely.
