### ISSUE TITLE
Can not playback note number 1-20 and 109-127 ?

### ISSUE THREAD

**Issue by cuonghh** [billthefarmer/mididriver#17]
Thanks for this library, it's very useful. 

But, when I build and test this lib, I can not playback note number from 1 to 20 and form 109 to 127 ?
_ sendMidi(0x90, 109,63): do not have any sound.
_ My phone uses android 4.1.1 and I build this code with android 4.0.3.

**Comment by billthefarmer** [comment]
I think this is due to the Sonivox midi synthesizer. I noticed something similar when testing my accordion app. It depends on which instrument you are using. I think they did this to reduce the size of the library - it's only about 300kb. It may be that the real instrument can't play those notes.
