### ISSUE TITLE
Undefined rederence

### ISSUE THREAD

**Issue by SynLocker** [billthefarmer/mididriver#20]
Hello, i am new with Android NDK so i don't know exactly what to do.

I have downloaded the driver from https://github.com/billthefarmer/mididriver/archive/master.zip and
i imported it in android studio.
Then i installed the Android NDK toolkit, downloaded the platform_external_sonivox from here https://github.com/android/platform_external_sonivox/archive/master.zip 
and extracted it in app\src\main (i included it in the build.gradle file)
but when i try to build the APK android studio give me the "undefined reference" error(http://it.tinypic.com/r/2u8dm9z/9).

What did i miss? (sorry for my bad english)

**Comment by billthefarmer** [comment]
It looks like your build is missing this line in Android.mk to link in the OpemSLES and log libraries.
```
LOCAL_LDLIBS := -lOpenSLES -llog
```
There is a smarek branch: https://github.com/billthefarmer/mididriver/tree/smarek that is intended for use with Gradle and Android Studio. However it doesn't include the app. If you just want to add midi functionality to an app , you can use the aar libraries here: https://github.com/billthefarmer/mididriver/releases/tag/v1.06.

**Comment by SynLocker** [comment]
it work very well! thank you
