### ISSUE TITLE
Costum soundfont is possible?

### ISSUE THREAD

**Issue by nnttoo** [billthefarmer/mididriver#21]
thank you for sharing
can i load costum soundfont (how)?

**Comment by billthefarmer** [comment]
I don't thinks so. The soundfonts are built into the source code of the synthesizer.

**Comment by nnttoo** [comment]
i found this code in eas.h

`EAS_LoadDLSCollection()`

but i don understand c language,,

**Comment by billthefarmer** [comment]
I hadn't noticed that, it's not in the docs at https://github.com/android/platform_external_sonivox/tree/master/docs. To test it, you need to add some code to MidiDriver.java:
``` java
    public  native boolean loadDLS(String path);
```
with the other native methods. and add three bits of code to midi.cpp:
``` c++
EAS_PUBLIC EAS_RESULT (*pEAS_LoadDLSCollection) (EAS_DATA_HANDLE pEASData,
						 EAS_HANDLE streamHandle,
						 EAS_FILE_LOCATOR locator);
// ...
// midi load dls
jboolean
Java_org_billthefarmer_mididriver_MidiDriver_loadDLS(JNIEnv *env,
						     jobject obj,
						     jstring jpath)
{
    jboolean isCopy;
    EAS_RESULT result;
    EAS_FILE file;

    if (pEASData == NULL || midiHandle == NULL)
	return JNI_FALSE;

    file.path = env->GetStringUTFChars(jpath, &isCopy);
    file.fd = 0;

    result = pEAS_LoadDLSCollection(pEASData, midiHandle, &file);

    env->ReleaseStringUTFChars(jpath, file.path);

    if (result != EAS_SUCCESS)
	return JNI_FALSE;

    return JNI_TRUE;
}
// ...
    pEAS_LoadDLSCollection = (EAS_PUBLIC EAS_RESULT (*)
			      (EAS_DATA_HANDLE pEASData,
			       EAS_HANDLE streamHandle,
			       EAS_FILE_LOCATOR locator))
        dlsym(libHandler, "EAS_LoadDLSCollection");
    if (!pEAS_LoadDLSCollection)
    {
        env->ThrowNew(linkageErrorClass,
		      "EAS_LoadDLSCollection resolution failed");
        return -1;
    }
```
The last bit of code goes on the end of ``JNI_OnLoad()```. This code builds OK, but I have no idea if it will work.

**Comment by nnttoo** [comment]
I have tried to compile .so file,, maybe I should learn it later, for now can you give .so file that has been compiled with the  code above?

**Comment by billthefarmer** [comment]
OK
[libmidi.zip](https://github.com/billthefarmer/mididriver/files/233337/libmidi.zip)

**Comment by nnttoo** [comment]
unfortunately it does not work, but thanks for your help.

`java.lang.UnsatisfiedLinkError: Native method not found: org.billthefarmer.mididriver.MidiDriver.loadDLS:(Ljava/lang/String;)Z`

**Comment by billthefarmer** [comment]
The DLS load code is in branch DLS on here. https://github.com/billthefarmer/mididriver/tree/DLS

**Comment by nnttoo** [comment]
i have tried this branch, no error, but loadDLS always return false,,  
maybe you are right, it is not possible for now?

**Comment by billthefarmer** [comment]
I have updated the code because the EAS_LoadDLSCollection, here https://github.com/android/platform_external_sonivox/blob/master/arm-wt-22k/lib_src/eas_public.c does two different things.
``` c++
EAS_PUBLIC EAS_RESULT EAS_LoadDLSCollection (EAS_DATA_HANDLE pEASData, EAS_HANDLE pStream, EAS_FILE_LOCATOR locator)
{
    EAS_FILE_HANDLE fileHandle;
    EAS_RESULT result;
    EAS_DLSLIB_HANDLE pDLS;

    if (pStream != NULL)
    {
        if (!EAS_StreamReady(pEASData, pStream))
            return EAS_ERROR_NOT_VALID_IN_THIS_STATE;
    }

    /* open the file */
    if ((result = EAS_HWOpenFile(pEASData->hwInstData, locator, &fileHandle, EAS_FILE_READ)) != EAS_SUCCESS)
        return result;

    /* parse the file */
    result = DLSParser(pEASData->hwInstData, fileHandle, 0, &pDLS);
    EAS_HWCloseFile(pEASData->hwInstData, fileHandle);

    if (result == EAS_SUCCESS)
    {
        /* if a stream pStream is specified, point it to the DLS collection */
        if (pStream)
            result = EAS_IntSetStrmParam(pEASData, pStream, PARSER_DATA_DLS_COLLECTION, (EAS_I32) pDLS);

        /* global DLS load */
        else
            result = VMSetGlobalDLSLib(pEASData, pDLS);
    }

    return result;
}
```
If the stream is null it does a global DLS load, so I have put another parameter in to do a global load to see if that might work.
``` java
 public native boolean loadDLS(String path, boolean global);
```

**Comment by billthefarmer** [comment]
DLS .aar files for Cody Eddings...
[MidiDriver-DLS.aar.zip](https://github.com/billthefarmer/mididriver/files/371064/MidiDriver-DLS.aar.zip)

**Comment by CodyEddings** [comment]
I've been unable to load in my custom DLS. So far, i've tried: 
```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        ...
        // Instantiate the driver.
        midiDriver = new MidiDriver();
        // Set the listener.
        midiDriver.setOnMidiStartListener(this);

       boolean test = false;
        String path = "android.resource://" + getPackageName() + "/" + R.raw.fury;
        midiDriver.loadDLS(path,test);
        if (test) {
            Toast.makeText(this, "DLS file loaded", Toast.LENGTH_SHORT);
        }
    }
```

It seems that "test" is always false. I've verified that I have a DLS file (fury.dls) located in the raw directory of my application. Am I using a correct implementation of loadDLS(string path, boolean global) or is it intended to be used differently?

**Comment by billthefarmer** [comment]
If you look at the comments above you can see that I put in the boolean parameter to determine whether to do a global load or not. I included an extract from the relevant code in the comment.
``` C++
    if (global)
	result = pEAS_LoadDLSCollection(pEASData, NULL, &file);

    else
	result = pEAS_LoadDLSCollection(pEASData, midiHandle, &file);

    env->ReleaseStringUTFChars(jpath, file.path);

    if (result != EAS_SUCCESS)
    {
	LOG_E(LOG_TAG, "Load DLS collection failed: %ld", result);
	return JNI_FALSE;
    }

return JNI_TRUE;
```
The return value is the success/fail notification, the boolean global determines what bit of code gets executed. I suggest you try it both ways. I suggest you do...
``` java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        ...
        // Instantiate the driver.
        midiDriver = new MidiDriver();
        // Set the listener.
        midiDriver.setOnMidiStartListener(this);

       boolean success = false;
       boolean test = false;
        String path = "android.resource://" + getPackageName() + "/" + R.raw.fury;
        success = midiDriver.loadDLS(path,test);
        if (success) {
            Toast.makeText(this, "DLS file loaded (global)", Toast.LENGTH_SHORT);
        }
       success = false;
       test = true;
        String path = "android.resource://" + getPackageName() + "/" + R.raw.fury;
        success = midiDriver.loadDLS(path,test);
        if (success) {
            Toast.makeText(this, "DLS file loaded (not global)", Toast.LENGTH_SHORT);
        }
    }
```

**Comment by CodyEddings** [comment]
Unforunately, `midiDriver.loadDLS(path,test);` returned false whether it was run with true or false for the global boolean. Are we out of options?

**Comment by loki666** [comment]
Using a file path in res/raw will never works since EAS will try to fopen() the path.
You need a file path that point to a file on the filesystem (ie: in /sdcard/).
Even like that I couldn't make it work. At best, it load the .DLS file OK, but it doesn't seem to actually use it.

**Comment by billthefarmer** [comment]
There is a further complication to this, around the time of Android 5.01, they changed the API for EAS_HWOpenFile(), and EAS_FILE_LOCATOR to use callbacks:
```
Author: Marco Nelissen <marcone@google.com>
Date:   Tue Dec 16 12:45:05 2014 -0800

    Use callbacks for I/O

    Instead of having the Sonivox engine directly open the file and
    use stdio to read from it, use caller-provided callbacks.
```
My code uses the old version. Now I have updated the driver to include the latest EAS Sonivox sources it's definitely not going to work. The driver doesn't support file IO, so it's not affected. If anyone is still interested in this, I could revert eas_hostmm.c and eas_types.h to the old version. I noticed a revision to DLS code in the commit history:
```
    Author: Eric Laurent <elaurent@google.com>
    Date:   Thu May 14 09:10:40 2015 -0700

    DLS parser: fix wave pool size check.

    Bug: 21132860.
```

**Comment by slesinger** [comment]
I'm interested to make it work. The default guitar sound is far from being usable. Thank you.

**Comment by billthefarmer** [comment]
You are welcome to fork the driver and have a go. The DLS branch contains the code I wrote to test and includes reverting eas_hostmm.c and eas_types.h to the old version as above.

**Comment by bmaupin** [comment]
I'm not sure if this is helpful at all, but this project supports soundfont2 files: https://github.com/KyoSherlock/MidiDriver

**Comment by bmaupin** [comment]
> i found this code in eas.h
> 
> `EAS_LoadDLSCollection()`
> 
> but i don understand c language,,

It looks like `EAS_LoadDLSCollection` was removed with this commit message:

> Remove unused code from midi engine

(https://android.googlesource.com/platform/external/sonivox/+/af41595537b044618234fe7dd9ebfcc652de1576%5E%21/#F1)

That might explain why it never worked :man_shrugging:

**Comment by M-HT** [comment]
If anyone is still interested in this, I recently made some changes in [this fork](https://github.com/pedrolcl/sonivox) of Sonivox EAS library to fix loading/using DLS files (at least some of them) using `EAS_LoadDLSCollection`. It shouldn't be difficult to adapt the changes to this project.
The relevant commits are:
* [Increase limits for loading DLS files](https://github.com/pedrolcl/sonivox/commit/7371b2ed46cbd2c092a78494ebab11212f57f3bf)
* [Improve searching for instruments in loaded DLS file](https://github.com/pedrolcl/sonivox/commit/6d6618d2f03c23158993d88b5886343340093cc2)

**Comment by valentinev-celadon** [comment]
@billthefarmer Hi boss. 
Will there be updates for connecting DLS?

**Comment by billthefarmer** [comment]
See the [README](https://github.com/billthefarmer/mididriver#load-dls-soundfont-files), #43.
