### ISSUE TITLE
Can't publish with code built using 32-bit ndk

### ISSUE THREAD

**Issue by shachar-oren** [billthefarmer/mididriver#34]
Hello there,
When I try to upload an aab file using this library, I get an error in the developer console:

> This release is not compliant with the Google Play 64-bit requirement
> 
> The following APKs or App Bundles are available to 64-bit devices, but they only have 32-bit native code: 3.
> 
> Include 64-bit and 32-bit native code in your app. Use the Android App Bundle publishing format to automatically ensure that each device architecture receives only the native code it needs. This avoids increasing the overall size of your app.

This check was added during a change on August 1, 2019 of the developer console.

From what I have read in other issues, 64-bit version of this lib is broken? It seems like I need a 64-bit version for the error to clear. How should I solve this?

**Comment by billthefarmer** [comment]
The latest [version](https://github.com/billthefarmer/mididriver/releases/tag/v1.17) of the driver contains 32 bit and bit copies of the library using a recent version of the Sonivox code. It should work fine on all devices. It looks like you may have inadvertently built 32 bit only versions of your app.

**Comment by bneumann** [comment]
Yes I can confirm it's working under 32/64 for x86 and ARM. Tested Android versions 4.4 to 9.

**Comment by shachar-oren** [comment]
> 
> 
>  you may have inadvertently built 32 bit only versions of your app.
Yep I did. I included only one copy of libmidi.so in project, so it was not generated for  x64. Thank you for the fast replies guys. Problem solved.
