### ISSUE TITLE
Does it support multiple drum kits?

### ISSUE THREAD

**Issue by davidmcasas** [billthefarmer/mididriver#38]
I was able to select different instruments, but I can't get to change the drum kit sounds. Not sure if I'm doing something wrong or there's just one kit. If it's posible to change the drumkit, what would be the code to do it? The default kit sounds a bit weak. Otherwise great tool, much appreciated.

**Comment by billthefarmer** [comment]
I have no idea. I am not a midi expert, the driver is just a wrapper around the Sonivox synthesizer built into android. [This file](https://github.com/billthefarmer/mididriver/blob/master/library/src/main/java/org/billthefarmer/mididriver/GeneralMidiConstants.java) lists all the midi instruments, also my [Accordion](https://github.com/billthefarmer/accordion) app allows any of them to be played.

**Comment by davidmcasas** [comment]
Some midi synths have multiple drum kits for the drum channel so they allow you to use different kit sounds for different music styles. These kits don't belong to the default instrument 0-127 list, that only applies for the instrument channels, not for the drum channel. I guess Sonivox is just limited to one default drum kit. Thank you anyway, really helpful driver.
