### ISSUE TITLE
how to play a chord?

### ISSUE THREAD

**Issue by fernandoavf7** [billthefarmer/mididriver#41]
Which would be the correct way to stream a chord? for example if I want to play a C major: C-E-G?

I tried in this way

```
event = new byte[3];
        event[0] = (byte) (0x90 | 0x00);
        event[1] = (byte) 60;
        event[2] = (byte) 0x7F;

event2 = new byte[3];
        event[0] = (byte) (0x90 | 0x01);
        event[1] = (byte) 65;
        event[2] = (byte) 0x7F;

event3 = new byte[3];
        event[0] = (byte) (0x90 | 0x02);
        event[1] = (byte) 68;
        event[2] = (byte) 0x7F

        midiDriver.write(event);
        midiDriver.write(event2);
        midiDriver.write(event3);
```

but is right?... and where can I learn more about the library? documentation or a extend guide. 

Thanks in advance

**Comment by billthefarmer** [comment]
This driver is just a wrapper around the Sonivox synthesizer included in every android device. You need to look up standard generic midi programming. However what I can say is that you must send a matching note off message for every note on and you don't need to use a different channel for each note unless you want to use a different instrument. See the code in the demo app [here](https://github.com/billthefarmer/mididriver/blob/869fc8811b93f4bea3238a5fb70f214249246bea/app/src/main/java/org/billthefarmer/miditest/MainActivity.java#L115).

**Comment by fernandoavf7** [comment]
Thank so much dear, with the example now it sounds better, but now I am searching how to change the instrument, I have read in some places but there are so much to understand before, I am on it... but, could you tell me how to do it please? 

I have found the MIDI specifications and I read that you have to set in the first 4 bytes of config, but I'am trying to do without success, always sound the piano, I think is the number 1 in the list;
![image](https://user-images.githubusercontent.com/26680776/116181258-4ed2e680-a6e8-11eb-9a5e-0dbed2f3f9ec.png)

`   byte msg[] = new byte[2];

        msg[0] = (byte) (0xC0 | 0x00);
        msg[1] = (byte) 25; //instrument
        midi.write(msg);`

**Comment by fernandoavf7** [comment]
Thank so much dear, with the example now it sounds better.
