### ISSUE TITLE
SIGSEGV from all versions above and including 1.22

### ISSUE THREAD

**Issue by Sola85** [billthefarmer/mididriver#46]
I'm getting crashes when initializing all recent versions of the library, starting with v1.22:

`A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 11423 (.appname), pid 11423 (.appname)`

I know that this feedback alone probably isn't very helpful, but I'm very inexperienced when it comes to debugging native code, so help or guidance on what further details that I could provide, would be very much appreciated.

**Comment by Sola85** [comment]
New information: the crash only happens when calling 
`midiDriver.stop()`
before calling 
`midiDriver.start()`
which previously worked fine. So this might be less of an issue after all.

**Comment by billthefarmer** [comment]
If you call ` midiDriver.start()` from `onResume()` and ` midiDriver.start()` from `onPause()` as per the [README](https://github.com/billthefarmer/mididriver#methods) then this can't happen, android takes care of it. I have added code to stop this which will be in the next version.
