### ISSUE TITLE
Oboe Callback blocked with mutex

### ISSUE THREAD

**Issue by ygtorres** [billthefarmer/mididriver#47]
One of the requirements when using audio thread is that any object shared with the audio thread have to be locked free, so why you use a mute when calling EAS_Render.  That is causing suboptimal timer accuracy.

**Comment by billthefarmer** [comment]
I agree that's what the docs say and expert advice says similar. However the Sonivox synthesizer isn't thread safe, so if an app calls `EAS_WriteMIDIStream()` while the synthesizer is processing `EAS_Render()` unexpected things happen. Using a mutex is the accepted way of handling this and that is what android does in `MidiFile.cpp`, which is the code that handles playing midi files. And that's where I originally got the ideas from to develop this driver.

**Comment by ygtorres** [comment]
Yes you are right, is not thread safe, and it's true in the code android has published to test the library, they use mutextes, only because it's converting midi to WAV. But that's no the right way. And if anyone needs to build a midi players, will notice the issue with time accuracy. I will close this issue, and when I have time I will share a solution for all of the people with that issue.

**Comment by ygtorres** [comment]
Playing single notes it's ok, the issue arise when you need it for a more
intensive task. For instance to create a live midi file player. That's
where you really notice the consequences of using a mutex in Audio Thread

**Comment by billthefarmer** [comment]
If you are using this driver to play midi files you are using the wrong software. `MidiFile.cpp` uses the `EAS_OpenFile()`/`EAS_Prepare()`/`EAS_CloseFile()`/etc API to play files. This driver is intended for musical instrument emulators or games where the midi messages should be limited to 2 or 3 bytes as per the test app.

**Comment by ygtorres** [comment]
Hi, thank you very much for taking your time to reply, it's ok. Base on
your driver I developed a new one it's not using any lock, I couldn't use
any of you suggestion because my midi files are generated on the fly and
while playing user can modify it's events so it's not possible to use a
plain midi file. User may also change tempo. So I needed a high performance
midi player, and now it's working perfectly fine. You can check it out here.

https://www.facebook.com/groups/402392864940112/?ref=share
