### ISSUE TITLE
Is it able to play midi file?

### ISSUE THREAD

**Issue by jeonhoeun** [billthefarmer/mididriver#49]
First of all, thank you for this good library.

I tried set mididriver on my android project.
It looks mididriver can play just one tick sound. 

If I want play midi file, is it posible?

**Comment by jeonhoeun** [comment]
I'm Sorry^;;..  your sample already have the sample ( play midi file )

**Comment by SmithGoll** [comment]
> I'm Sorry^;;..  your sample already have the sample ( play midi file )

To be honest, that ant.mid file in example is actually played using an Android player
mididriver currently does not have the ability to play MIDI files.
