### ISSUE TITLE
Not playing the higher or lower note when the program change to Harmonica

### ISSUE THREAD

**Issue by xingxing21** [billthefarmer/mididriver#50]
Hi.
I'm testing this driver that plays the midi note on Android.
When I change the program to Harmonica, I can't hear the higher or lower note.
I can play the higher/lower note with Harmonica on a PC Windows
How can I fix this issue? Any idea?
Thanks

**Comment by billthefarmer** [comment]
See #17. A harmonica has a limited range, I expect Sonivox limited the range of the instruments to reduce the size of the synthesizer, bearing in mind it was originally written around 2008 in the early days of android.
